### ISSUE TITLE
Explosions can ignite building plans

### ISSUE THREAD

**Issue by KarolOfGutovo** [cit1zen/workers-and-resources-disasters-expanded#3]
![image](https://user-images.githubusercontent.com/46822289/181007155-5c2c40ad-6b8d-4b26-a9ed-edf6ebc0c0f9.png)
I was testing this mod out, and after a few buildings burned down and the schematics were placed, other explosions could ignite the construction site. This is a minor issue I guess, but it is an issue.

**Comment by cit1zen** [comment]
Thanks for reporting. I will try to fix it in 0.2.0 that should be out next week.

**Comment by cit1zen** [comment]
Solved in 0.1.1
